// <auto-generated />
using System;
using DataBase.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DataBase.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20220628105443_DisciplineLectorBugfix")]
    partial class DisciplineLectorBugfix
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DataBase.Models.Assistant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateCreate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DateUpdate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("DisciplineId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TeacherId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DisciplineId");

                    b.HasIndex("TeacherId");

                    b.ToTable("Assistants");
                });

            modelBuilder.Entity("DataBase.Models.Discipline", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateCreate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DateUpdate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("LectorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Semester")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("LectorId");

                    b.ToTable("Disciplines");
                });

            modelBuilder.Entity("DataBase.Models.Group", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateCreate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DateUpdate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("DataBase.Models.Lesson", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DateCreate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DateUpdate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("DisciplineId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("LessonTypeId")
                        .HasColumnType("uuid");

                    b.Property<int>("SequenceNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DisciplineId");

                    b.HasIndex("LessonTypeId");

                    b.ToTable("Lessons");
                });

            modelBuilder.Entity("DataBase.Models.LessonsVisitors", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateCreate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DateUpdate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("LessonId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("StatusOnLessonId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("StudentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("LessonId");

                    b.HasIndex("StatusOnLessonId");

                    b.HasIndex("StudentId");

                    b.ToTable("LessonsVisitors");
                });

            modelBuilder.Entity("DataBase.Models.LessonType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateCreate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DateUpdate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("EnumId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("LessonTypes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6aa74582-0eba-4eee-a960-3b6fc3092130"),
                            DateCreate = new DateTime(2022, 6, 28, 13, 54, 43, 344, DateTimeKind.Local).AddTicks(2678),
                            DateUpdate = new DateTime(2022, 6, 28, 13, 54, 43, 344, DateTimeKind.Local).AddTicks(2687),
                            EnumId = 1,
                            Name = "Лекция"
                        },
                        new
                        {
                            Id = new Guid("3e46ecb0-a6e6-49eb-9f9e-32daa6595bc9"),
                            DateCreate = new DateTime(2022, 6, 28, 13, 54, 43, 344, DateTimeKind.Local).AddTicks(2741),
                            DateUpdate = new DateTime(2022, 6, 28, 13, 54, 43, 344, DateTimeKind.Local).AddTicks(2742),
                            EnumId = 2,
                            Name = "Лабораторная работа"
                        },
                        new
                        {
                            Id = new Guid("f69a359a-4986-4253-9409-078660dc8fc8"),
                            DateCreate = new DateTime(2022, 6, 28, 13, 54, 43, 344, DateTimeKind.Local).AddTicks(2755),
                            DateUpdate = new DateTime(2022, 6, 28, 13, 54, 43, 344, DateTimeKind.Local).AddTicks(2755),
                            EnumId = 3,
                            Name = "Семинар"
                        });
                });

            modelBuilder.Entity("DataBase.Models.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DateCreate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DateUpdate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Midname")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("DataBase.Models.StatusOnLesson", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateCreate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DateUpdate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("EnumId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("StatusOnLessons");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6aa74582-0eba-4eee-a960-3b6fc3092130"),
                            DateCreate = new DateTime(2022, 6, 28, 13, 54, 43, 344, DateTimeKind.Local).AddTicks(2772),
                            DateUpdate = new DateTime(2022, 6, 28, 13, 54, 43, 344, DateTimeKind.Local).AddTicks(2773),
                            EnumId = 1,
                            Name = "Присутствовал"
                        },
                        new
                        {
                            Id = new Guid("3e46ecb0-a6e6-49eb-9f9e-32daa6595bc9"),
                            DateCreate = new DateTime(2022, 6, 28, 13, 54, 43, 344, DateTimeKind.Local).AddTicks(2787),
                            DateUpdate = new DateTime(2022, 6, 28, 13, 54, 43, 344, DateTimeKind.Local).AddTicks(2788),
                            EnumId = 2,
                            Name = "Отсутствовал"
                        },
                        new
                        {
                            Id = new Guid("f69a359a-4986-4253-9409-078660dc8fc8"),
                            DateCreate = new DateTime(2022, 6, 28, 13, 54, 43, 344, DateTimeKind.Local).AddTicks(2800),
                            DateUpdate = new DateTime(2022, 6, 28, 13, 54, 43, 344, DateTimeKind.Local).AddTicks(2800),
                            EnumId = 3,
                            Name = "Освобожден"
                        },
                        new
                        {
                            Id = new Guid("bc9474a1-4fb2-4638-b1c4-f4ca21c68bb9"),
                            DateCreate = new DateTime(2022, 6, 28, 13, 54, 43, 344, DateTimeKind.Local).AddTicks(2813),
                            DateUpdate = new DateTime(2022, 6, 28, 13, 54, 43, 344, DateTimeKind.Local).AddTicks(2813),
                            EnumId = 4,
                            Name = "Другая подгруппа"
                        });
                });

            modelBuilder.Entity("DataBase.Models.Student", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateCreate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DateUpdate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PersonId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("PersonId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("DataBase.Models.Teacher", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateCreate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DateUpdate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("PersonId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("Teachers");
                });

            modelBuilder.Entity("DataBase.Models.Assistant", b =>
                {
                    b.HasOne("DataBase.Models.Discipline", "Discipline")
                        .WithMany()
                        .HasForeignKey("DisciplineId");

                    b.HasOne("DataBase.Models.Teacher", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId");

                    b.Navigation("Discipline");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("DataBase.Models.Discipline", b =>
                {
                    b.HasOne("DataBase.Models.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId");

                    b.HasOne("DataBase.Models.Teacher", "Lector")
                        .WithMany()
                        .HasForeignKey("LectorId");

                    b.Navigation("Group");

                    b.Navigation("Lector");
                });

            modelBuilder.Entity("DataBase.Models.Lesson", b =>
                {
                    b.HasOne("DataBase.Models.Discipline", "Discipline")
                        .WithMany()
                        .HasForeignKey("DisciplineId");

                    b.HasOne("DataBase.Models.LessonType", "LessonType")
                        .WithMany()
                        .HasForeignKey("LessonTypeId");

                    b.Navigation("Discipline");

                    b.Navigation("LessonType");
                });

            modelBuilder.Entity("DataBase.Models.LessonsVisitors", b =>
                {
                    b.HasOne("DataBase.Models.Lesson", "Lesson")
                        .WithMany()
                        .HasForeignKey("LessonId");

                    b.HasOne("DataBase.Models.StatusOnLesson", "StatusOnLesson")
                        .WithMany()
                        .HasForeignKey("StatusOnLessonId");

                    b.HasOne("DataBase.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId");

                    b.Navigation("Lesson");

                    b.Navigation("StatusOnLesson");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("DataBase.Models.Student", b =>
                {
                    b.HasOne("DataBase.Models.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId");

                    b.HasOne("DataBase.Models.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId");

                    b.Navigation("Group");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("DataBase.Models.Teacher", b =>
                {
                    b.HasOne("DataBase.Models.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId");

                    b.Navigation("Person");
                });
#pragma warning restore 612, 618
        }
    }
}
